import Head from 'next/head';
import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header className={styles.header}>
				<p>
					Header
				</p>
			</header>

			<main>
				Main
			</main>

			<footer>
				Footer
			</footer>
		</div>
	)
}
